version: "3"

services:
  postgres:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=revou
      - POSTGRES_USER=revou
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
